/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LicenseRouteImport } from './routes/license'
import { Route as ContributingRouteImport } from './routes/contributing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReleasesIndexRouteImport } from './routes/releases/index'
import { Route as ReleasesLatestRouteImport } from './routes/releases/latest'
import { Route as ReleasesTagRouteImport } from './routes/releases/$tag'
import { ServerRoute as ApiWebhookReleaseServerRouteImport } from './routes/api/webhook/release'
import { ServerRoute as ApiWebhookReleasePrereleaseServerRouteImport } from './routes/api/webhook/release_.prerelease'

const rootServerRouteImport = createServerRootRoute()

const LicenseRoute = LicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributingRoute = ContributingRouteImport.update({
  id: '/contributing',
  path: '/contributing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesIndexRoute = ReleasesIndexRouteImport.update({
  id: '/releases/',
  path: '/releases/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesLatestRoute = ReleasesLatestRouteImport.update({
  id: '/releases/latest',
  path: '/releases/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesTagRoute = ReleasesTagRouteImport.update({
  id: '/releases/$tag',
  path: '/releases/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookReleaseServerRoute = ApiWebhookReleaseServerRouteImport.update({
  id: '/api/webhook/release',
  path: '/api/webhook/release',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiWebhookReleasePrereleaseServerRoute =
  ApiWebhookReleasePrereleaseServerRouteImport.update({
    id: '/api/webhook/release_/prerelease',
    path: '/api/webhook/release/prerelease',
    getParentRoute: () => rootServerRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contributing': typeof ContributingRoute
  '/license': typeof LicenseRoute
  '/releases/$tag': typeof ReleasesTagRoute
  '/releases/latest': typeof ReleasesLatestRoute
  '/releases': typeof ReleasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contributing': typeof ContributingRoute
  '/license': typeof LicenseRoute
  '/releases/$tag': typeof ReleasesTagRoute
  '/releases/latest': typeof ReleasesLatestRoute
  '/releases': typeof ReleasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contributing': typeof ContributingRoute
  '/license': typeof LicenseRoute
  '/releases/$tag': typeof ReleasesTagRoute
  '/releases/latest': typeof ReleasesLatestRoute
  '/releases/': typeof ReleasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contributing'
    | '/license'
    | '/releases/$tag'
    | '/releases/latest'
    | '/releases'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contributing'
    | '/license'
    | '/releases/$tag'
    | '/releases/latest'
    | '/releases'
  id:
    | '__root__'
    | '/'
    | '/contributing'
    | '/license'
    | '/releases/$tag'
    | '/releases/latest'
    | '/releases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContributingRoute: typeof ContributingRoute
  LicenseRoute: typeof LicenseRoute
  ReleasesTagRoute: typeof ReleasesTagRoute
  ReleasesLatestRoute: typeof ReleasesLatestRoute
  ReleasesIndexRoute: typeof ReleasesIndexRoute
}
export interface FileServerRoutesByFullPath {
  '/api/webhook/release': typeof ApiWebhookReleaseServerRoute
  '/api/webhook/release/prerelease': typeof ApiWebhookReleasePrereleaseServerRoute
}
export interface FileServerRoutesByTo {
  '/api/webhook/release': typeof ApiWebhookReleaseServerRoute
  '/api/webhook/release/prerelease': typeof ApiWebhookReleasePrereleaseServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/webhook/release': typeof ApiWebhookReleaseServerRoute
  '/api/webhook/release_/prerelease': typeof ApiWebhookReleasePrereleaseServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/webhook/release' | '/api/webhook/release/prerelease'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/webhook/release' | '/api/webhook/release/prerelease'
  id: '__root__' | '/api/webhook/release' | '/api/webhook/release_/prerelease'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiWebhookReleaseServerRoute: typeof ApiWebhookReleaseServerRoute
  ApiWebhookReleasePrereleaseServerRoute: typeof ApiWebhookReleasePrereleaseServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/license': {
      id: '/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof LicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributing': {
      id: '/contributing'
      path: '/contributing'
      fullPath: '/contributing'
      preLoaderRoute: typeof ContributingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases/': {
      id: '/releases/'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof ReleasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases/latest': {
      id: '/releases/latest'
      path: '/releases/latest'
      fullPath: '/releases/latest'
      preLoaderRoute: typeof ReleasesLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases/$tag': {
      id: '/releases/$tag'
      path: '/releases/$tag'
      fullPath: '/releases/$tag'
      preLoaderRoute: typeof ReleasesTagRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/webhook/release': {
      id: '/api/webhook/release'
      path: '/api/webhook/release'
      fullPath: '/api/webhook/release'
      preLoaderRoute: typeof ApiWebhookReleaseServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/webhook/release_/prerelease': {
      id: '/api/webhook/release_/prerelease'
      path: '/api/webhook/release/prerelease'
      fullPath: '/api/webhook/release/prerelease'
      preLoaderRoute: typeof ApiWebhookReleasePrereleaseServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContributingRoute: ContributingRoute,
  LicenseRoute: LicenseRoute,
  ReleasesTagRoute: ReleasesTagRoute,
  ReleasesLatestRoute: ReleasesLatestRoute,
  ReleasesIndexRoute: ReleasesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiWebhookReleaseServerRoute: ApiWebhookReleaseServerRoute,
  ApiWebhookReleasePrereleaseServerRoute:
    ApiWebhookReleasePrereleaseServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
